name = "sub1"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "1504c93a983a4a7586a235350f42edb9" }
]
